deckhouse/sds-local-volume

crds/localstorageclass.yaml, images/sds-local-volume-controller/api/v1alpha1/local_storage_class.go, images/sds-local-volume-controller/cmd/main.go, images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher.go, images/sds-local-volume-csi/driver/controller.go, images/sds-local-volume-csi/internal/const.go
Added a new field for the LocalStorageClass resource's Spec named lvm. 
New field provides better resource's structure.
Nothing special: everything should work the same way.
=> [controller] Add spec.lvm to a LocalStorageClass resource

images/sds-local-volume-scheduler-extender/pkg/scheduler/filter.go, images/sds-local-volume-scheduler-extender/pkg/scheduler/prioritize.go
Fixed free space calculation logic for PVCs using the same storage class. 
It solves the problem with insufficient free space for PVCs using the same storage class. Before it was counted for each one independently.
A pod with several PVCs using the same storage class will not be scheduled, if there is not enough free space on the node for all PVCs.
=> [controller] Fixed free space calculation logic for PVCs using the same storage class

crds/localstorageclass.yaml, images/sds-local-volume-controller/cmd/main.go, images/sds-local-volume-controller/pkg/config/config.go, images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher.go
Add a possibility to edit a LocalStorageClass spec.lvm.LVMVolumeGroups resources to configure an appropriate Storage Class.
Now if the resource validation fails, the controller will add a request to requeue until the resource is fixed or deleted.
A user has a possibility to change LVMVolumeGroups using by a Storage Class.
If a user fixes the LocalStorageClass validation failure, the controller will continue the work automatically.
A LocalStorageClass spec.lvm.LVMVolumeGroups editing provides an appropriate Storage Class recreation with actual LVMVolumeGroups.
If the validation of the Local Storage Class resource fails, the controller will retry processing the resource until it succeeds or the problematic resource is deleted.
=> [contoller] Add a possibility to edit a LocalStorageClass spec.lvm.LVMVolumeGroups to configure an appropriate Storage Class.

images/sds-local-volume-csi/driver/node.go, images/sds-local-volume-scheduler-extender/pkg/scheduler/filter.go
Signed-off-by: Viktor Kramarenko <viktor.kramarenko@flant.com>
In a really high PVC amount scenario there is a chance to face Volume limit and concurrent map access problems.
It solves the volume limit and concurrent map access problems.
Any amount of volumes might be attached to a node. No errors with concurrent map access.
=> [controller] Fix max volumes per node and R/W map

images/sds-local-volume-scheduler-extender/go.mod, images/sds-local-volume-scheduler-extender/pkg/scheduler/filter.go, images/sds-local-volume-scheduler-extender/pkg/scheduler/prioritize.go, images/sds-local-volume-scheduler-extender/pkg/scheduler/prioritize_test.go, openapi/config-values.yaml, templates/sds-local-volume-scheduler-extender/configmap.yaml
More informative logs and more accurate node scoring.
More informative logs and more accurate node scoring.
More informative logs and more accurate node scoring.
=> [controller] Add logs and upgrading node scoring

templates/sds-local-volume-scheduler-extender/configmap.yaml
Fix KubeSchedulerConfiguration API version
kubescheduler.config.k8s.io/v1beta3 is removed in k8s 1.29, so kubescheduler can't be launched
Working kubescheduler on k8s 1.29
=> Fix KubeSchedulerConfiguration API version

images/sds-local-volume-controller/api/v1alpha1/lvm_volume_group.go, images/sds-local-volume-csi/api/v1alpha1/lvm_volume_group.go, images/sds-local-volume-csi/driver/controller.go, images/sds-local-volume-csi/pkg/utils/func.go, images/sds-local-volume-scheduler-extender/api/v1alpha1/lvm_volume_group.go, images/sds-local-volume-scheduler-extender/pkg/controller/lvg_watcher_cache.go, images/sds-local-volume-scheduler-extender/pkg/scheduler/filter.go, images/sds-local-volume-scheduler-extender/pkg/scheduler/prioritize.go
Refactoring due to size field type changes from string to quantity.
Less parsing and more accurate code.
No type string for any size field of any resource.
=> [controller] Change LVMVolumeGroup size field type from string to quantity

images/sds-local-volume-controller/api/v1alpha1/sds_local_volume_config.go, images/sds-local-volume-controller/cmd/main.go, images/sds-local-volume-controller/go.mod, images/sds-local-volume-controller/pkg/config/config.go, images/sds-local-volume-controller/pkg/controller/local_csi_node_watcher.go, images/sds-local-volume-controller/pkg/controller/local_csi_node_watcher_test.go, images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher.go, templates/sds-local-volume-controller/rbac-for-us.yaml
The controller adds a special label to nodes which local-csi-node pods will be scheduled on, based on user's preferences.
A user specifies the labels, which will be used by the controller to identify desired nodes where the local-csi-node pods should be scheduled on.
The controller uses the labels as a match-selector to select the nodes and label them with its own label, which is the 
actual trigger to place the local-csi-node pods on the nodes. 
Without the label, local-csi-node pods are not able to be scheduled or run.
Local-csi-node pods are scheduled on the exact nodes with user's labels. 
If the user removes the label from the node, the corresponding local-csi-node pod got removed.
=> [controller] Add a controller to label nodes for sds-local-volume-csi

images/sds-local-volume-scheduler-extender/pkg/cache/cache.go, images/sds-local-volume-scheduler-extender/pkg/cache/cache_test.go, images/sds-local-volume-scheduler-extender/pkg/controller/lvg_watcher_cache.go, images/sds-local-volume-scheduler-extender/pkg/scheduler/filter.go
Refactored LVMVolumeGroup's updates in the cache, tests fixes and minor logs adding.
Prevent several bugs, more informative logs.
No problems with using LVMVolumeGroups which have been created after scheduler's start.
=> [controller] Add some logic refactoring and minor fixes

templates/sds-local-volume-controller/deployment.yaml
Add controller's pods antiaffinity rules
We need to use different nodes while HA mode is switch on
Working antiaffinity rules
=> [controller] add pod antiaffinity rules

images/sds-local-volume-controller/api/v1alpha1/lvm_volume_group.go, images/sds-local-volume-csi/Dockerfile, images/sds-local-volume-csi/api/v1alpha1/lvm_volume_group.go, images/sds-local-volume-csi/cmd/main.go, images/sds-local-volume-csi/driver/controller.go, images/sds-local-volume-csi/pkg/utils/func.go, images/sds-local-volume-scheduler-extender/api/v1alpha1/lvm_volume_group.go, images/sds-local-volume-scheduler-extender/pkg/cache/cache.go, images/sds-local-volume-scheduler-extender/pkg/cache/cache_test.go, images/sds-local-volume-scheduler-extender/pkg/consts/consts.go, images/sds-local-volume-scheduler-extender/pkg/controller/lvg_watcher_cache.go, images/sds-local-volume-scheduler-extender/pkg/controller/pvc_watcher_cache.go, images/sds-local-volume-scheduler-extender/pkg/scheduler/filter.go, images/sds-local-volume-scheduler-extender/pkg/scheduler/filter_test.go, images/sds-local-volume-scheduler-extender/pkg/scheduler/prioritize.go, images/sds-local-volume-scheduler-extender/pkg/scheduler/route.go
Added a support for an AllocationLimit feature. It allows users to manage LVMVolumeGroup thin-pool's available space through the AllocationLimit field, so they can easily decrease or increase the amount of thin LV using the thin-pools.
The controller will filter and score the nodes according to the AllocationLimit value.
It prevents unexpected and unmanageable Thin LV creations and disk space overuse.
The controller filters and scores the nodes for Thin LVs correctly according to AllocationLimit value. 
Thin LVs with requested size more than available thin pool space, should not be created (but might become such, if a user increase the AllocationLimit value).
=> [controller] Add AllocationLimit feature support

images/sds-local-volume-csi/api/v1alpha1/lvm_logical_volume.go, images/sds-local-volume-csi/pkg/utils/func.go
Added contiguous field to LVMLogicalVolume Status field to sync data objects between different modules.
Consistent data objects.
Nothing fails, LVMLogicalVolume resources are created successfully.
=> [controller] Added contiguous to LVMLogicalVolumeStatus

hooks/generate_scheduler_extender_certs.py, hooks/generate_webhook_certs.py, images/sds-local-volume-csi/driver/controller.go, images/sds-local-volume-csi/pkg/utils/func.go, images/sds-local-volume-scheduler-extender/src/cmd/cmd/root.go, images/sds-local-volume-scheduler-extender/src/go.mod, images/sds-local-volume-scheduler-extender/src/pkg/scheduler/filter.go, images/sds-local-volume-scheduler-extender/src/pkg/scheduler/func.go, images/sds-local-volume-scheduler-extender/src/pkg/scheduler/func_test.go, images/sds-local-volume-scheduler-extender/src/pkg/scheduler/prioritize.go, images/sds-local-volume-scheduler-extender/src/pkg/scheduler/route.go, openapi/values.yaml, templates/sds-local-volume-scheduler-extender/configmap.yaml, templates/sds-local-volume-scheduler-extender/deployment.yaml, templates/sds-local-volume-scheduler-extender/kube-scheduler-webhook-configuration.yaml, templates/sds-local-volume-scheduler-extender/rbac-for-us.yaml, templates/sds-local-volume-scheduler-extender/secret.yaml, templates/sds-local-volume-scheduler-extender/service.yaml, templates/webhooks/webhook.yaml
This PR transitions from using a dedicated scheduler with an extender for pods that utilize specific PVCs with `local.csi.storage.deckhouse.io` provisioner to a centralized approach provided by Deckhouse. Previously, a separate scheduler was required for each SDS module. With the introduction of the `KubeSchedulerWebhookConfiguration` resource in Deckhouse, we now configure the extender-scheduler directly within the default scheduler, eliminating the need for module-specific schedulers.
The previous method required maintaining a separate scheduler for each SDS module, leading to complexity and potential overhead. By adopting the `KubeSchedulerWebhookConfiguration`, we streamline the configuration process, reduce resource duplication, and centralize scheduler-extender configuration. This …
=> [scheduler] New way to add scheduler-extender

docs/README.md, docs/README.ru.md
Small fixes in documentation links
Correct documentation
=> [docs] Small docs fixes

LICENSE
Adding LICENSE file
It will enable us using https://pkg.go.dev/license-policy
License is present and we are able to see published symbols there: https://pkg.go.dev/github.com/deckhouse/sds-local-volume/api/v1alpha1
=> [docs] Add LICENSE

images/sds-local-volume-controller/src/go.mod, images/sds-local-volume-controller/src/go.sum, images/sds-local-volume-csi/src/go.mod, images/sds-local-volume-csi/src/go.sum, images/sds-local-volume-csi/src/pkg/kubutils/kubernetes.go, images/sds-local-volume-scheduler-extender/src/go.mod, images/sds-local-volume-scheduler-extender/src/go.sum, images/webhooks/src/go.mod, images/webhooks/src/go.sum, templates/sds-local-volume-csi/controller.yaml, templates/sds-local-volume-csi/rbac-for-us.yaml
Add a separate ServiceAccount for the csi-node.
Fix the csi-node pods startup after adding the [Deckhouse hook](https://github.com/deckhouse/deckhouse/blob/b2e60c1d9020a7366c214795dbc9d05ed7717316/modules/002-deckhouse/hooks/disable_sa_token_automount.go). 
Ensure the csi-node pods start successfully.
=> [csi] Add a separate ServiceAccount for the csi-node

docs/README.md, docs/README.ru.md
Documentation misses an important restriction about LVG usage in LocalStorageClasses. This fix adds it.
Keep documentation up to date
=> [Doc ] add restriction of usage thin LVGs in LocalStorageClasses

templates/csi/controller.yaml
Previous fix have a typo, so this must fix situation with snapshotter container presence in CE version
No snapshotter container in CE version
=> [internal] fix snapshotter container presence in CE version

images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher_func.go, images/sds-local-volume-controller/pkg/controller/local_storage_class_watcher_test.go, images/sds-local-volume-controller/pkg/internal/const.go
Add auto VolumeSnapshotClass annotations to StorageClasses
Correct snapshot work
=> [internal] add volumesnapshotclassname annotations to storageclasses

images/sds-local-volume-csi/driver/node.go, templates/csi/controller.yaml
Add NodeGetVolumeStats func for CSI
More function supports in CSI
=> [csi] add NodeGetVolumeStats func for CSI
