images/sds-lvm-controller/Makefile, images/sds-lvm-scheduler-extender/cmd/cmd/root.go, images/sds-lvm-scheduler-extender/pkg/scheduler/filter.go, images/sds-lvm-scheduler-extender/pkg/scheduler/prioritize.go, images/sds-lvm-scheduler-extender/pkg/scheduler/route.go
Updated scheduler filter and prioritize logic. 
Reworked score nodes algorithm.
=> [controller] New version of extender scheduler

.github/PULL_REQUEST_TEMPLATE.md
Every PR will have standard template
=> [docs] Add pull request template

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/PULL_REQUEST_TEMPLATE.md
Issue template will be added to github repository
All future issues will be standard documented
Every new issue will have standard template
=> [docs] Add Issue templates

.github/checkPreviousChannelRelease.sh, .github/workflows/deploy_prod.yml
We need only sequential release deploy to channels
We must prevent non-sequential release deploy
Correct previous channel release check
=> Add previous channel release version check

openapi/config-values.yaml, templates/sds-local-volume-controller/secret.yaml, templates/sds-local-volume-csi/controller.yaml
Add user node selector for data nodes
We must set node-selector for sds-node-configurator daemonset
Correct sds-node-configurator work
=> Add user node selector for data nodes

images/webhooks/src/validators/storageClassUpdate.go, templates/webhooks/rbac-for-us.yaml
Fixed default Storage Class validation
Now default storage class validation working incorrect
Correct storage class validation
=> [controller] Fixed default Storage Class validation

.github/workflows/deploy_prod.yml
Fix previous release check
Now we have incorrect steps order in workflow
Correct previous release check
=> [ci] Fix previous release check

.github/workflows/deploy_prod.yml
Fix previous release check
Now we have incorrect steps order in workflow
Correct previous release check
=> [ci] Fix previous release check (2)

docs/README.md, docs/README.ru.md
Change the module status from `experimental` to `preview`.
The status of the module in the documentation is `preview`.
=> [docs] Change the module status to `preview`

docs/README.md, docs/README.ru.md
Fix in docs
There is some incorrect points in module configuration instruction
Correct docs
=> [docs] Fixes in docs

docs/README.ru.md
Small fix in docs
Actual documentation in module
=> [docs] small fix

images/sds-local-volume-controller/cmd/main.go, images/sds-local-volume-controller/pkg/config/config.go, images/sds-local-volume-csi/cmd/main.go, images/sds-local-volume-csi/config/config.go, images/sds-local-volume-scheduler-extender/cmd/cmd/root.go, images/sds-local-volume-scheduler-extender/config/config.go, templates/sds-local-volume-controller/deployment.yaml, templates/sds-local-volume-csi/controller.yaml, templates/sds-local-volume-scheduler-extender/configmap.yaml, templates/sds-local-volume-scheduler-extender/deployment.yaml
Add liveness and readiness checks to controller
Correct checks of deployment
=> [controller] add liveness and readiness checks

images/sds-local-volume-controller/go.mod, images/sds-local-volume-controller/go.sum, images/sds-local-volume-csi/driver/controller.go, images/sds-local-volume-csi/go.mod, images/sds-local-volume-csi/go.sum, images/sds-local-volume-csi/pkg/utils/func.go, images/sds-local-volume-scheduler-extender/go.mod, images/sds-local-volume-scheduler-extender/go.sum
Updated sds-node-configurator api module 
More consistent code.
Everything works fine.
=> [controller] Update sds-node-configurator api model

docs/FAQ.md, docs/FAQ.ru.md
Add data migration script to FAQ
In some cases users may want to move data from one PVC to another
Migration script in docs for such cases
=> [docs] Add data migration script to FAQ

.github/workflows/go_modules_check.yaml, images/sds-local-volume-controller/src/go.mod, images/sds-local-volume-controller/src/go.sum, images/sds-local-volume-csi/go.mod, images/sds-local-volume-csi/go.sum, images/sds-local-volume-scheduler-extender/src/go.mod, images/sds-local-volume-scheduler-extender/src/go.sum, images/webhooks/src/go.mod, images/webhooks/src/go.sum
Add check for our golang API modules
Actual golang API modules in our repositories
=> [CI] Check Go modules version

images/sds-local-volume-controller/src/go.mod, images/sds-local-volume-controller/src/go.sum, images/sds-local-volume-csi/go.mod, images/sds-local-volume-csi/go.sum, images/sds-local-volume-scheduler-extender/src/go.mod, images/sds-local-volume-scheduler-extender/src/go.sum, images/webhooks/src/go.mod, images/webhooks/src/go.sum
Updated modules go.mod to actual api module state.
Actual and consistent data to work with.
Everything works fine, no checks failed.
=> [controller] Fix imports check

.github/workflows/trivy_check.yaml, trivy.yaml
Add Trivy vulnerables check (also fixes one vulnerable in go code)
Modules without known vulnerables
=> [CI] Add Trivy vulnerables check

images/webhooks/src/handlers/lscValidator.go
I've tried to create this resource:
```
apiVersion: storage.deckhouse.io/v1alpha1
kind: LocalStorageClass
metadata:
name: lsc-thin
spec:
lvm:
lvmVolumeGroups:
- name: vg-1
type: Thin    
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
and got this error:
```
[...] There must be only thin pools with Thin LVM type
```
After the change it will look like:
```
There must be only thin pools with Thin LVM type. Found: vg-1.
```
It will reduce time needed to understand the problem.
Message becomes clear.
=> [controller] Improve lsc validation error message

images/sds-local-volume-csi/werf.inc.yaml
Remove unnecessary images
We must have only necessary images in module
Correct module build
=> [internal] Remove unnecessary images

crds/localstorageclass.yaml
We need to backup our CRs
Our internal backup mechanism needs label on CRD to recognize it
Correct backup work
=> [internal] Add backup control label

.github/workflows/build_prod.yml, .github/workflows/deploy_prod.yml
Added secondary repo in build and SE+ version
Image digests must be consistent.
SE+ version must exists.
=> [CI] Add secondary repo in build and SE+ version

templates/sds-local-volume-scheduler-extender/configmap.yaml, templates/sds-local-volume-scheduler-extender/deployment.yaml, templates/sds-local-volume-scheduler-extender/kube-scheduler-webhook-configuration.yaml, templates/sds-local-volume-scheduler-extender/service.yaml, templates/webhooks/webhook.yaml
This is automated change made with this script:
```
#!/bin/bash
set -e
git clone git@github.com:deckhouse/sds-local-volume.git
find ./ -type f -name "*.yaml" -exec sed -i 's/(eq "dev" .Values.global.deckhouseVersion)/(or (hasPrefix "dev" .Values.global.deckhouseVersion) (hasSuffix "dev" .Values.global.deckhouseVersion))/g' {} +
BRANCH_NAME="astef-dev-in-tag-fix"  # Unique branch name with timestamp
for dir in */; do
echo "Repository: $dir"
cd "$dir"
if [[ -n $(git status --porcelain) ]]; then
git checkout -b "$BRANCH_NAME"
git add .
git commit -s -m "Automated commit. See script in PR"
git push -u origin "$BRANCH_NAME"
echo "Changes pushed to branch: $BRANCH_NAME"
else
echo "No changes detected"
fi
cd - > /dev/null
done
```
See https://github.com/deckhouse/sds-replicated-volume/pull/211
- …
=> [ci] dev in tag fix (automatic)

docs/README.md, docs/README.ru.md
=>  [docs] fixed moduletag

images/sds-local-volume-controller/go.mod, images/sds-local-volume-controller/go.sum, images/sds-local-volume-csi/go.mod, images/sds-local-volume-csi/go.sum, images/sds-local-volume-scheduler-extender/go.mod, images/sds-local-volume-scheduler-extender/go.sum, images/webhooks/go.mod, images/webhooks/go.sum, templates/csi/controller.yaml
We have problem with some clusters because of missed param in CSI
Correct DS render
=> [internal] Fixes issue with DS deploy

.github/workflows/build_dev.yml, .github/workflows/build_prod.yml, .github/workflows/deploy_dev.yml, .github/workflows/go_checks.yaml, .github/workflows/trivy_image_check.yaml, module.yaml, templates/controller/deployment.yaml, trivy-silent.yaml, trivy.yaml, werf.yaml
Fixes in CI, module structure and build
Correct module lifecycle
=> [internal] Fixes in CI, module structure and build

werf.yaml
Fix module name
Correct module structure
=> Fix module name

.werf/choose-edition.yaml
There is some logic issues in CRDs labels and module version image. This PR fixes it
Correct module work
=> Fix module CRDs and choose-version image if needed

templates/csi/controller.yaml
Fix unnecessary csi snapshotter container in CE version
Correct module templates
=> [internal] Remove snapshotter from CE

docs/README.md, docs/README.ru.md
Add snapshot-controller requirement info
Correct documentation
=> [internal] add snapshot-controller requirement info

templates/controller/deployment.yaml
Fix container readable root by replacing privileged security context with read-only root filesystem and dropped capabilities
Fix container readable root
Secure module
=> [internal] fix container readable root
